export const VEHICLE_LIST_REQUEST= 'VEHICLE_LIST_REQUEST';
export const VEHICLE_LIST_SUCCESS= 'VEHICLE_LIST_SUCCESS';
export const VEHICLE_LIST_FAIL= 'VEHICLE_LIST_FAIL';

export const VEHICLE_DETAIL_REQUEST= 'VEHICLE_DETAIL_REQUEST';
export const VEHICLE_DETAIL_SUCCESS= 'VEHICLE_DETAIL_SUCCESS';
export const VEHICLE_DETAIL_FAIL= 'VEHICLE_DETAIL_FAIL';

export const VEHICLE_DELETE_REQUEST= 'VEHICLE_DELETE_REQUEST';
export const VEHICLE_DELETE_SUCCESS= 'VEHICLE_DELETE_SUCCESS';
export const VEHICLE_DELETE_FAIL= 'VEHICLE_DELETE_FAIL';
export const VEHICLE_DELETE_RESET = 'PRODUCT_DELETE_RESET';